server:
  ip: "127.0.0.1"
  port: 8080
  root: "root"

logging:
  level: "debug"
  file: "server.log"

#temp
database:
  uri: "mongodb://lockr_app:password@127.0.0.1:27017/lockr?authSource=lockr"
  name: "lockr"